### ISSUE TITLE
CI configuration should use PDK (not bundler, rake, etc.)

### ISSUE THREAD

**Issue by bittner** [puppetlabs/pdk-module-template#58]
Currently, the only CI configuration we generate prepares bundler, rake, etc. for execution. The whole setup is verbose and looks a bit complicated at first sight. (Full disclosure: I'm not a Ruby developer.)

Proposed Solution
--------------

The CI configuration should be as concise, simple, readable, self-explanatory as possible. It should use PDK for simplicity. Examples:

```yaml
# Travis CI configuration
---
install:
  - wget 'https://pm.puppetlabs.com/cgi-bin/pdk_download.cgi?dist=ubuntu&rel=16.04&arch=amd64&ver=latest' -q -O pdk.deb && dpkg -i pdk.deb && rm pdk.deb

script:
  - pdk validate 2> /dev/null
  - pdk test unit 2> /dev/null
```
```yaml
# GitLab CI configuration
---
before_script:
  - wget 'https://pm.puppetlabs.com/cgi-bin/pdk_download.cgi?dist=ubuntu&rel=16.04&arch=amd64&ver=latest' -q -O pdk.deb && dpkg -i pdk.deb && rm pdk.deb

validate:
  stage: build
  script:
    - pdk validate 2> /dev/null

test:
  stage: test
  script:
    - pdk test unit 2> /dev/null
```
```yaml
# Bitbucket Pipelines configuration
---
image: ruby:2.3.0

pipelines:
  default:
    - step:
      script:
        - wget 'https://pm.puppetlabs.com/cgi-bin/pdk_download.cgi?dist=ubuntu&rel=16.04&arch=amd64&ver=latest' -q -O pdk.deb && dpkg -i pdk.deb && rm pdk.deb
        - pdk validate 2> /dev/null
        - pdk test unit 2> /dev/null
```

**NOTE:** Both the complicated-looking `wget` and `2> /dev/null` construct are things that should go away soon, according to open tickets in the Puppet Labs issue tracker.

Related Issues
------------

- https://github.com/puppetlabs/pdk/issues/315 (~ Support several CI services)
- https://github.com/puppetlabs/pdk/issues/323 (~ Make PDK silent for CI)
- https://github.com/puppetlabs/pdk/issues/324 (~ Install PDK from .deb/.rpm/etc.)
- https://github.com/puppetlabs/pdk/issues/336 (~ Provide Docker image for CI)
